files: .
repos:
  - repo: local
    hooks:
      - id: format
        name: run formatting
        entry: black .
        language: python
        types: [python]
        stages: [push]
        always_run: true